baseURL: 'https://web3yoda.dev'
theme: Yoda's Note
themesDir: themes
title: Yoda's Note
defaultContentLanguage: zh-cn
languageCode: zh-cn
languageName: 简体中文
hasCJKLanguage: false
paginate: 12
googleAnalytics: G-J3NCP3DPFH
copyright: ''
enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true
ignoreErrors:
  - error-remote-getjson
  - error-missing-instagram-accesstoken
author:
  name: Yoda
  email: 'yoda@w3m.org'
  link: ''
menu:
  main:
    - weight: 1
      identifier: posts
      pre: ''
      post: ''
      name: Posts
      url: /posts/
      title: ''
    - weight: 2
      identifier: tags
      pre: ''
      post: ''
      name: Tags
      url: /tags/
      title: ''
    - weight: 3
      identifier: categories
      pre: ''
      post: ''
      name: Categories
      url: /categories/
      title: ''
params:
  defaultTheme: auto
  gitRepo: 'https://github.com/web3yoda'
  fingerprint: ''
  dateFormat: '2006-01-02'
  title: Yoda's Note
  description: Yet another developer's tech notes.
  images:
    - /logo.png
  header:
    desktopMode: fixed
    mobileMode: auto
    title:
      logo: ''
      name: Yoda's Note
      pre: ''
      post: ''
      typeit: false
  footer:
    enable: true
    custom: ''
    hugo: true
    copyright: true
    author: true
    since: 2019
    icp: ''
    license: >-
      <a rel="license external nofollow noopener noreffer"
      href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC
      BY-NC 4.0</a>
  section:
    paginate: 20
    dateFormat: 01-02
    rss: 10
  list:
    paginate: 20
    dateFormat: 01-02
    rss: 10
  app:
    title: LoveIt
    noFavicon: false
    svgFavicon: ''
    themeColor: '#ffffff'
    iconColor: '#5bbad5'
    tileColor: '#da532c'
  search:
    enable: true
    type: algolia
    contentLength: 4000
    placeholder: ''
    maxResultLength: 10
    snippetLength: 30
    highlightTag: em
    absoluteURL: false
    algolia:
      index: ''
      appID: ''
      searchKey: ''
  home:
    rss: 10
    profile:
      enable: true
      # gravatarEmail: yoda@w3m.dev
      avatarURL: images/avatar.jpg
      title: ''
      subtitle: Yet another developer's tech notes
      typeit: true
      social: true
      disclaimer: ''
    posts:
      enable: true
      paginate: 6
  social:
  page:
    hiddenFromHomePage: false
    hiddenFromSearch: false
    twemoji: false
    lightgallery: false
    ruby: true
    fraction: true
    fontawesome: true
    linkToMarkdown: true
    rssFullText: false
    toc:
      enable: true
      keepStatic: false
      auto: true
    code:
      copy: true
      maxShownLines: 50
    math:
      enable: false
      inlineLeftDelimiter: ''
      inlineRightDelimiter: ''
      blockLeftDelimiter: ''
      blockRightDelimiter: ''
      copyTex: true
      mhchem: true
    mapbox:
      accessToken: >-
        pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ
      lightStyle: 'mapbox://styles/mapbox/light-v10?optimize=true'
      darkStyle: 'mapbox://styles/mapbox/dark-v10?optimize=true'
      navigation: true
      geolocate: true
      scale: true
      fullscreen: true
    share:
      enable: true
      Twitter: true
      Facebook: true
      Linkedin: false
      Whatsapp: false
      Pinterest: false
      Tumblr: false
      HackerNews: true
      Reddit: false
      VK: false
      Buffer: false
      Xing: false
      Line: true
      Instapaper: false
      Pocket: false
      Flipboard: false
      Weibo: true
      Blogger: false
      Baidu: false
      Odnoklassniki: false
      Evernote: false
      Skype: false
      Trello: false
      Mix: false
    comment:
      enable: true
      disqus:
        enable: false
        shortname: ''
      gitalk:
        enable: false
        owner: ''
        repo: ''
        clientId: ''
        clientSecret: ''
      valine:
        enable: false
        appId: 
        appKey: 
        placeholder: ''
        avatar: mp
        meta: ''
        pageSize: 10
        lang: ''
        visitor: true
        recordIP: true
        highlight: true
        enableQQ: false
        serverURLs: ''
        emoji: ''
      facebook:
        enable: false
        width: 100%
        numPosts: 10
        appId: ''
        languageCode: ''
      telegram:
        enable: false
        siteID: ''
        limit: 5
        height: ''
        color: ''
        colorful: true
        dislikes: false
        outlined: false
      commento:
        enable: false
      utterances:
        enable: false
        repo: ''
        issueTerm: pathname
        label: ''
        lightTheme: github-light
        darkTheme: github-dark
      giscus:
        enable: true
        repo: web3yoda/comments
        repoId: R_kgDOJmLJDQ
        category: Announcements
        categoryId: DIC_kwDOJmLJDc4CWqXv
        lang: en
        mapping: pathname
        reactionsEnabled: '1'
        emitMetadata: '0'
        inputPosition: top
        lazyLoading: false
        lightTheme: light
        darkTheme: dark
    library:
      css: {}
      js: {}
    seo:
      images: []
      publisher:
        name: web3yoda
        logoUrl: /images/avatar.jpg
  typeit:
    speed: 100
    cursorSpeed: 1000
    cursorChar: '|'
    duration: -1
  verification:
    google: ''
    bing: ''
    yandex: ''
    pinterest: ''
    baidu: ''
  seo:
    image: /images/Apple-Devices-Preview.png
    thumbnailUrl: /images/screenshot.png
  analytics:
    enable: true
    google:
      id: G-J3NCP3DPFH
      anonymizeIP: true
    fathom:
      id: ''
      server: ''
    plausible:
      dataDomain: ''
    yandexMetrica:
      id: ''
  cookieconsent:
    enable: false
    content:
      message: ''
      dismiss: ''
      link: ''
  cdn:
    data: jsdelivr.yml
  compatibility:
    polyfill: false
    objectFit: false
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
Permalinks:
  posts: ':filename'
privacy:
  googleAnalytics: {}
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
mediaTypes:
  text/plain:
    suffixes:
      - md
outputFormats:
  MarkDown:
    mediaType: text/plain
    isPlainText: true
    isHTML: false
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - MarkDown
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML
languages:
  en:
    weight: 1
    languageCode: en
    languageName: English
    hasCJKLanguage: false
    copyright: >-
      This work is licensed under a Creative Commons Attribution-NonCommercial
      4.0 International License.
    menu:
      main:
        - weight: 1
          identifier: posts
          pre: ''
          post: ''
          name: Posts
          url: /posts/
          title: ''
        - weight: 2
          identifier: tags
          pre: ''
          post: ''
          name: Tags
          url: /tags/
          title: ''
        - weight: 3
          identifier: categories
          pre: ''
          post: ''
          name: Categories
          url: /categories/
          title: ''
        - weight: 4
          identifier: documentation
          pre: ''
          post: ''
          name: Docs
          url: /categories/documentation/
          title: ''
        - weight: 5
          identifier: cheatsheet
          pre: ''
          post: ''
          name: Cheatsheet
          url: /developer-cheatsheet/
          title: ''
        - weight: 6
          identifier: about
          pre: ''
          post: ''
          name: About
          url: /about/
          title: ''
        - weight: 7
          identifier: github
          pre: <i class='fab fa-github fa-fw' aria-hidden='true'></i>
          post: ''
          name: ''
          url: 'https://github.com/web3yoda'
          title: GitHub
    params:
      search:
        enable: true
        type: algolia
        contentLength: 4000
        placeholder: ''
        maxResultLength: 10
        snippetLength: 30
        highlightTag: em
        absoluteURL: false
        algolia:
          index: index.en
          appID: PASDMWALPK
          searchKey: b42948e51daaa93df92381c8e2ac0f93
      home:
        rss: 10
        profile:
          enable: true
          # gravatarEmail: yoda@w3m.dev
          avatarURL: /images/avatar.jpg
          title: ''
          subtitle: Yet another developer's tech notes
          typeit: true
          social: true
          disclaimer: ''
      social:
        GitHub: web3yoda
        Twitter: web3_yoda
        Youtubechannel: '@web3yoda'
        Zhihu: web3yoda
        Bilibili: 1013505916
        Email: yoda@w3m.dev
        RSS: true
  zh-cn:
    weight: 2
    languageCode: zh-CN
    languageName: 简体中文
    hasCJKLanguage: true
    copyright: >-
      This work is licensed under a Creative Commons Attribution-NonCommercial
      4.0 International License.
    menu:
      main:
        - weight: 1
          identifier: posts
          pre: ''
          post: ''
          name: 所有文章
          url: /posts/
          title: ''
        - weight: 2
          identifier: tags
          pre: ''
          post: ''
          name: 标签
          url: /tags/
          title: ''
        - weight: 3
          identifier: categories
          pre: ''
          post: ''
          name: 分类
          url: /categories/
          title: ''
        - weight: 4
          identifier: documentation
          pre: ''
          name: 文档
          url: /categories/documentation/
          title: ''
        - weight: 5
          identifier: cheatsheet
          pre: ''
          post: ''
          name: Cheatsheet
          url: /developer-cheatsheet/
          title: ''
        - weight: 6
          identifier: about
          pre: ''
          post: ''
          name: 关于
          url: /about/
          title: ''
        - weight: 7
          identifier: github
          pre: <i class='fab fa-github fa-fw' aria-hidden='true'></i>
          post: ''
          name: ''
          url: 'https://github.com/web3yoda/web3yoda.github.io'
          title: GitHub
    params:
      search:
        enable: true
        type: algolia
        contentLength: 4000
        placeholder: ''
        maxResultLength: 10
        snippetLength: 50
        highlightTag: em
        absoluteURL: false
        algolia:
          index: index.zh-cn
          appID: PASDMWALPK
          searchKey: b42948e51daaa93df92381c8e2ac0f93
      home:
        rss: 10
        profile:
          enable: true
          # gravatarEmail: yoda@w3m.dev
          avatarURL: /images/avatar.jpg
          title: ''
          subtitle: 一个开发者的技术笔记
          typeit: true
          social: true
          disclaimer: ''
      social:
        GitHub: web3yoda
        Twitter: web3_yoda
        Youtubechannel: '@web3yoda'
        Zhihu: web3yoda
        Bilibili: 1013505916
        Email: yoda@w3m.dev
        RSS: true